async function fetchBotResponse(userMessage) {
    const response = await fetch('https://api.openai.com/v1/engines/davinci-codex/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `sk-proj-PmwwZm5dDXpnkkUb0rPJT3BlbkFJcCjPMdTcQqbckUbtTAp9`
        },
        body: JSON.stringify({
            prompt: userMessage,
            max_tokens: 150,
            temperature: 0.7
        })
    });

    const data = await response.json();
    const botMessage = data.choices[0].text.trim();
    displayMessage(botMessage, 'bot');
}
